#!usr/bin/env bash

# LS
alias ls='ls --color=auto'
alias ll='ls -alh'

# TREE
alias tree='tree -C'

# GREP
alias grep='grep -n --color=auto'
alias gg='git grep -n'
alias ggi='git grep -n -i'

# FIND
alias ff='find . -name'
alias ffi='find . -iname'

# FREE
alias free='free -h'
alias freee='sudo sysctl -w vm.drop_caches=3'
