#!usr/bin/env bash

# LS
alias ls='ls --color=auto'
alias ll='ls -alh'

# TREE
alias tree='tree -C'

# GREP
alias grep='grep -n --color=auto'
alias gg='git grep -n'
alias ggi='git grep -n -i'

# FIND
alias ff='find . -name'
alias ffi='find . -iname'

# FREE
alias free='free -h'
alias freee='sudo sysctl -w vm.drop_caches=3'

# VALGRIND
alias V='valgrind --leak-check=full --show-leak-kinds=all'

# ROBOT
alias robot='PYTHONDONTWRITEBYTECODE=1 robot --output NONE --report NONE --log NONE'

# PYTHON
alias python='PYTHONDONTWRITEBYTECODE=1 python'
alias python3='PYTHONDONTWRITEBYTECODE=1 python3'
